# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aoctl < Formula
  desc "Advent of Code CLI to help you organize and test your solutions"
  homepage "https://github.com/dolfolife/aoctl"
  version "0.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dolfolife/aoctl/releases/download/v0.0.9/aoctl_Darwin_x86_64.tar.gz"
      sha256 "fa342c6800c6bbb27451fbcec9f077683b8325c752ad5341b7ab31093a439f12"

      def install
        bin.install "aoctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dolfolife/aoctl/releases/download/v0.0.9/aoctl_Darwin_arm64.tar.gz"
      sha256 "f7a7c92f7a869f335764fa781ed7c3793e788cf529b2a6625733ed001089e375"

      def install
        bin.install "aoctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dolfolife/aoctl/releases/download/v0.0.9/aoctl_Linux_arm64.tar.gz"
      sha256 "6f140ed985994b60e47a1620b440dfc20d2191c91e5562fd55fbaf06eba77614"

      def install
        bin.install "aoctl"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dolfolife/aoctl/releases/download/v0.0.9/aoctl_Linux_armv6.tar.gz"
      sha256 "8f43b27b531b07f37dc4e5dfefa531706f197a833161858566c7afb41ae0a5f4"

      def install
        bin.install "aoctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dolfolife/aoctl/releases/download/v0.0.9/aoctl_Linux_x86_64.tar.gz"
      sha256 "5b4bb946b2f42df55ec2163a3ae55e576a107be2968fc2b7c96d47169a9d3555"

      def install
        bin.install "aoctl"
      end
    end
  end

  test do
    system "#{bin}/aoctl --version"
  end
end
