# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aoctl < Formula
  desc "Advent of Code CLI to help you organize and test your solutions"
  homepage "https://github.com/dolfolife/adventofcode"
  version "0.0.5"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dolfolife/adventofcode/releases/download/v0.0.5/adventofcode_Darwin_x86_64.tar.gz"
      sha256 "f4d6fa70443fe0955aa4e366c345624ad17dcd2300d517394c27c24bd59d04b1"

      def install
        bin.install "adventofcode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dolfolife/adventofcode/releases/download/v0.0.5/adventofcode_Darwin_arm64.tar.gz"
      sha256 "03830652d2e4d300a01f08fc7266e094cd7e3ee4825d65de979f6571852aef12"

      def install
        bin.install "adventofcode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dolfolife/adventofcode/releases/download/v0.0.5/adventofcode_Linux_arm64.tar.gz"
      sha256 "10003b033f0d033d35fb8f03292704ea78848048b6c19f397ce32d3be5f1ef1e"

      def install
        bin.install "adventofcode"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dolfolife/adventofcode/releases/download/v0.0.5/adventofcode_Linux_x86_64.tar.gz"
      sha256 "5570c890b1a05ff8a59a4e77f6773e9feb9f35a01cb70099ad838f7da81324d8"

      def install
        bin.install "adventofcode"
      end
    end
  end

  test do
    system "#{bin}/aoctl --version"
  end
end
